services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    inertia.service:
        class: InertiaBundle\Service\Inertia
        public: false
        arguments:
            $engine: '@twig'
            $requestStack: '@request_stack'
            $container: '@service_container'
            $serializer: '@serializer'

    InertiaBundle\Service\Inertia: '@inertia.service'

    inertia.areabrick_renderer:
        class: InertiaBundle\Service\AreabrickRenderer
        public: false
        arguments:
            $documentResolver: '@Pimcore\Http\Request\Resolver\DocumentResolver'

    InertiaBundle\Service\AreabrickRenderer: '@inertia.areabrick_renderer'
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    inertia.gateway:
        class: InertiaBundle\Support\SsrGateway
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $inertia: '@inertia.service'

    inertia.twig_extension:
        class: InertiaBundle\Twig\InertiaExtension
        public: false
        arguments:
            $inertia: '@inertia.service'
            $gateway: '@inertia.gateway'
        tags:
            - { name: twig.extension }

    InertiaBundle\Service\ThumbnailGenerator:
        arguments:
            $container: '@service_container'

    InertiaBundle\Service\TranslationService:
        arguments:
            $translator: '@Pimcore\Translation\Translator'
            $localeService: '@Pimcore\Localization\LocaleService'

    InertiaBundle\EventSubscriber\InertiaSubscriber:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            - { name: kernel.event_listener, event: kernel.response }
        arguments:
            $inertia: '@inertia.service'
            $csrfTokenManager: '@security.csrf.token_manager'
            $debug: '%kernel.debug%'
            $container: '@service_container'

    InertiaBundle\EventSubscriber\InertiaAttributeSubscriber:
        tags:
            - { name: kernel.event_listener, event: kernel.view }
        arguments:
            $inertia: '@inertia.service'
            $translationService: '@InertiaBundle\Service\TranslationService'

    InertiaBundle\Command\InstallAssetsCommand:
        class: InertiaBundle\Command\InstallAssetsCommand
        arguments:
            $kernel: '@kernel'
        tags: [ 'console.command' ]

    InertiaBundle\Command\InertiaStartSsr:
        class: InertiaBundle\Command\InertiaStartSsr
        tags: [ 'console.command' ]

    InertiaBundle\Command\InertiaStopSsr:
        class: InertiaBundle\Command\InertiaStopSsr
        tags: [ 'console.command' ]
        calls:
            - setContainer: [ '@service_container' ]

    InertiaBundle\Controller\AssetApiController:
        class: InertiaBundle\Controller\AssetApiController
        tags: [ 'controller.service_arguments' ]
        calls:
            - setServiceContainer: [ '@service_container' ]
            - setThumbnailGenerator: [ '@InertiaBundle\Service\ThumbnailGenerator' ]

    InertiaBundle\Controller\Admin\AssetCacheController:
        class: InertiaBundle\Controller\Admin\AssetCacheController
        tags: [ 'controller.service_arguments' ]

    InertiaBundle\EventSubscriber\InertiaAdminListener:
        arguments:
            $container: '@service_container'
        tags:
            - { name: kernel.event_listener, event: pimcore.bundle_manager.paths.js, method: addJsPaths }

    InertiaBundle\EventSubscriber\AssetCacheInvalidationListener:
        tags:
            - { name: kernel.event_listener }
            - { name: kernel.event_listener }

    InertiaBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('InertiaBundle')"